export const studentName = "Alice";
export let age = 20;
export let isEnrolled = true;
export const score = 9007199254740993n;
export const id = Symbol("id");
export const favoriteColors = ["red", "blue"];
export const profile = { name: studentName, age };
export const nothing = null;
export let notDefined;
export const PI;
