name: Autograding Tests

on:
  push:
  pull_request:
  workflow_dispatch:
  repository_dispatch:

permissions:
  checks: write
  actions: read
  contents: read

jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Run ESLint (no var allowed)
        run: npm run lint

      - name: Run Jest tests
        run: npm test

      - name: Calculate grade summary
        run: npm run grade

      - name: Upload raw test results
        uses: actions/upload-artifact@v4
        with:
          name: jest-results
          path: results.json

      - name: Autograding Reporter
        uses: classroom-resources/autograding-grading-reporter@v1
        with:
          runners: jest-tests
        env:
          JEST-TESTS_RESULTS: "${{ steps.Run\ Jest\ tests.outcome }}"
